<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_product' => [[], ['_controller' => 'App\\Controller\\AdminController::adminProduct'], [], [['text', '/admin/product/']], [], []],
    'admin_product_add' => [[], ['_controller' => 'App\\Controller\\AdminController::adminProductAdd'], [], [['text', '/admin/product/add']], [], []],
    'admin_product_update' => [['id'], ['_controller' => 'App\\Controller\\AdminController::adminProductUpdate'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product/update']], [], []],
    'admin_product_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminController::adminProductDelete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/product/delete']], [], []],
    'base' => [[], ['_controller' => 'App\\Controller\\BaseController::index'], [], [['text', '/base']], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/panier']], [], []],
    'cart_add' => [['id'], ['_controller' => 'App\\Controller\\OrderController::cartAdd'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/cart/add']], [], []],
    'cart_delete' => [[], ['_controller' => 'App\\Controller\\OrderController::cartDelete'], [], [['text', '/cart_delete']], [], []],
    'cart_item_delete' => [['key'], ['_controller' => 'App\\Controller\\OrderController::cartItemDelete'], [], [['variable', '/', '[^/]++', 'key'], ['text', '/cart_item_delete']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/']], [], []],
    'product' => [['slug'], ['_controller' => 'App\\Controller\\ProductController::product'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/product']], [], []],
    'category' => [['slug'], ['_controller' => 'App\\Controller\\ProductController::category'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/category']], [], []],
    'recherche' => [[], ['_controller' => 'App\\Controller\\ProductController::search'], [], [['text', '/recherche/']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/inscription']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/connexion']], [], []],
    'login_check' => [[], ['_controller' => 'App\\Controller\\UserController::loginCheck'], [], [['text', '/connexion_check']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/deconnexion']], [], []],
];
