<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQb9roi3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQb9roi3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQb9roi3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQb9roi3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQb9roi3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Qb9roi3',
    'container.build_id' => 'ae21064d',
    'container.build_time' => 1583509668,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQb9roi3');
